#!/usr/bin/env python3
"""FAZ 3 seed: starter control catalogs + matrix index (defense-only).

Generates YAML+Markdown control cards with framework mappings.
Idempotent: overwrites known CTRL-* starter files; leaves CTRL-SAMPLE-*.

Usage:
  python3 scripts/giga_security_faz3_seed.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

GUARD = (
    "> DEFENSE-ONLY: detection, hardening, compliance, IR playbooks. "
    "No exploits, phishing, malware, C2, ransomware, bypass, weaponized PoCs. "
    "ATT&CK only for detection/D3FEND mapping. "
    "Secrets: ${VAR}|vault://|op://|<REDACTED> only."
)

# Catalog: dir -> list of control dicts
# Fields: id, ad, aciklama, nist_csf, n80053, iso, cis, owasp, dogrulama, gerekce

CATALOGS: dict[str, list[dict]] = {
    "LAYERS": [
        {
            "id": "CTRL-L-001",
            "ad": "Politika katmanı — güvenlik politikası envanteri",
            "aciklama": "Yazılı güvenlik politikalarının (kabul edilebilir kullanım, erişim, olay) envanteri ve sahipliği.",
            "nist_csf": ["Govern", "Identify"],
            "n80053": ["PL-1", "PL-2"],
            "iso": ["A.5.1", "A.5.2"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "Politika listesi + son gözden geçirme tarihi; POLICY/ veya docs/ altında pointer.",
            "gerekce": "Katmanlı savunmanın L0 temeli; ölçülebilir politika olmadan kontrol boşluğu kapanmaz.",
        },
        {
            "id": "CTRL-L-002",
            "ad": "Kimlik katmanı — ayrıcalıklı erişim envanteri",
            "aciklama": "İnsan ve iş yükü kimliklerinin ayrıcalık sınıflandırması; break-glass vault:// referansı.",
            "nist_csf": ["Protect"],
            "n80053": ["AC-2", "AC-6"],
            "iso": ["A.5.15", "A.8.2"],
            "cis": ["CIS-5", "CIS-6"],
            "owasp": ["A01:2021"],
            "dogrulama": "Rol matrisi ORG/ROLES + erişim inceleme takvimi CALENDAR/.",
            "gerekce": "Yetkisiz yükseltme tespitini kolaylaştırır; least privilege için ön koşul.",
        },
        {
            "id": "CTRL-L-003",
            "ad": "Ağ katmanı — güven sınırları diyagramı",
            "aciklama": "Trust boundary’lerin dokümante edilmesi (CI runner, GitHub, yerel agent, harici API).",
            "nist_csf": ["Identify", "Protect"],
            "n80053": ["SC-7", "CA-3"],
            "iso": ["A.8.20", "A.8.22"],
            "cis": ["CIS-12"],
            "owasp": [],
            "dogrulama": "SECURITY_CONTEXT/trust-boundaries.md güncelliği.",
            "gerekce": "Segmentasyon ve firewall kurallarının hedefi netleşir.",
        },
        {
            "id": "CTRL-L-004",
            "ad": "Host katmanı — runner/OS sertleştirme kontrol listesi",
            "aciklama": "CI/CD runner ve geliştirme VM’leri için ASSESS-ONLY sertleştirme checklist’i.",
            "nist_csf": ["Protect"],
            "n80053": ["CM-6", "SI-2"],
            "iso": ["A.8.9"],
            "cis": ["CIS-4", "CIS-10"],
            "owasp": [],
            "dogrulama": "ASSESSMENTS/host-hardening.md veya gap satırı.",
            "gerekce": "Tedarik zinciri ve runner kaçırma yüzeyini daraltır.",
        },
        {
            "id": "CTRL-L-005",
            "ad": "Uygulama katmanı — girdi doğrulama standardı",
            "aciklama": "Python CLI argümanları ve agent çıktıları için doğrulama/sanitize standardı (defense).",
            "nist_csf": ["Protect"],
            "n80053": ["SI-10"],
            "iso": ["A.8.28"],
            "cis": ["CIS-16"],
            "owasp": ["A03:2021"],
            "dogrulama": "scripts/ argparse kullanımı örnek incelemesi; SECURITY_QA checklist.",
            "gerekce": "Injection ve path traversal sınıfı kusurları önler (kod üretimi bağlamında).",
        },
        {
            "id": "CTRL-L-006",
            "ad": "Veri katmanı — sınıflandırma şeması",
            "aciklama": "Public / Internal / Confidential / Secret sınıfları; Secret yalnızca ${VAR}|vault://.",
            "nist_csf": ["Identify", "Protect"],
            "n80053": ["MP-3", "SC-28"],
            "iso": ["A.5.12", "A.8.11"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "SECURITY_CONTEXT/data-classes.md.",
            "gerekce": "Şifreleme ve erişim kontrollerinin kapsamını belirler.",
        },
        {
            "id": "CTRL-L-007",
            "ad": "Tespit katmanı — log/telemetri minimum set",
            "aciklama": "AUDIT_LOG.jsonl, workflow logları, secret_scan/ethics_check çıktıları için minimum görünürlük.",
            "nist_csf": ["Detect"],
            "n80053": ["AU-2", "AU-6"],
            "iso": ["A.8.15", "A.8.16"],
            "cis": ["CIS-8"],
            "owasp": ["A09:2021"],
            "dogrulama": "validate.yml + secret_scan hook kanıtı REPORTS/.",
            "gerekce": "Olay yanıtı ve uyumluluk için izlenebilirlik.",
        },
        {
            "id": "CTRL-L-008",
            "ad": "Yanıt katmanı — IR playbook iskeleti",
            "aciklama": "Olay sınıflandırma, iletişim, containment ASSESS-ONLY adımları.",
            "nist_csf": ["Respond"],
            "n80053": ["IR-4", "IR-8"],
            "iso": ["A.5.24", "A.5.26"],
            "cis": ["CIS-17"],
            "owasp": [],
            "dogrulama": ".cursor/skills/incident-response/references/playbook-skeleton.md.",
            "gerekce": "Olay anında karar gecikmesini azaltır.",
        },
        {
            "id": "CTRL-L-009",
            "ad": "Kurtarma katmanı — yedek/geri alma planı",
            "aciklama": "Git history + branch koruması; kritik docs için snapshot ARCHIVE/.",
            "nist_csf": ["Recover"],
            "n80053": ["CP-9", "CP-10"],
            "iso": ["A.8.13"],
            "cis": ["CIS-11"],
            "owasp": [],
            "dogrulama": "ARCHIVE/ ve branch protection ASSESS notu.",
            "gerekce": "Yanlış commit/sızıntı sonrası hızlı geri dönüş.",
        },
        {
            "id": "CTRL-L-010",
            "ad": "Tedarik zinciri katmanı — bağımlılık sınırı",
            "aciklama": "katalog/ vendored; root’ta pip/npm yok; CI pin’li actions.",
            "nist_csf": ["Protect", "Identify"],
            "n80053": ["SA-12", "CM-8"],
            "iso": ["A.5.19", "A.5.21"],
            "cis": ["CIS-16"],
            "owasp": ["A06:2021"],
            "dogrulama": "AGENTS.md + validate workflows; SBOM stub sbom-provenance.",
            "gerekce": "Üçüncü parti risk yüzeyini bilinçli tutar.",
        },
        {
            "id": "CTRL-L-011",
            "ad": "Agent güvenlik katmanı — ethics guardrail",
            "aciklama": "05-ethics-guardrail + ethics_check.py; offensive içerik reddi.",
            "nist_csf": ["Govern", "Protect"],
            "n80053": ["PL-4", "SI-4"],
            "iso": ["A.5.1"],
            "cis": ["CIS-14"],
            "owasp": [],
            "dogrulama": "python3 scripts/ethics_check.py --self-test.",
            "gerekce": "AI ajanların dual-use üretmesini engeller.",
        },
        {
            "id": "CTRL-L-012",
            "ad": "Gizlilik katmanı — PII minimizasyonu",
            "aciklama": "AUDIT/raporlarda kişisel veri yok; örneklerde <REDACTED>.",
            "nist_csf": ["Protect"],
            "n80053": ["SI-12", "MP-6"],
            "iso": ["A.5.34"],
            "cis": ["CIS-3"],
            "owasp": ["A01:2021"],
            "dogrulama": "secret_scan + manuel örnek tarama.",
            "gerekce": "KVKK/GDPR uyumlu dokümantasyon hijyeni.",
        },
        {
            "id": "CTRL-L-013",
            "ad": "Değişiklik katmanı — MODE geçiş kaydı",
            "aciklama": "ASSESS-ONLY → IMPLEMENT geçişleri açık kapsam + STATE damgası.",
            "nist_csf": ["Govern"],
            "n80053": ["CM-3"],
            "iso": ["A.8.32"],
            "cis": ["CIS-16"],
            "owasp": [],
            "dogrulama": "SECURITY/STATE.md mode alanı.",
            "gerekce": "Kontrol uygulamasında yetkisiz değişiklik riskini keser.",
        },
        {
            "id": "CTRL-L-014",
            "ad": "Şeffaflık katmanı — karar gerekçesi",
            "aciklama": "Her kontrol kartında savunma_gerekçesi ve doğrulama yöntemi zorunlu.",
            "nist_csf": ["Govern"],
            "n80053": ["AU-3"],
            "iso": ["A.5.8"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "compliance-mapper field contract.",
            "gerekce": "Denetlenebilir, tekrar edilebilir güvenlik kararları.",
        },
        {
            "id": "CTRL-L-015",
            "ad": "Süreklilik katmanı — aylık arşiv",
            "aciklama": "ARCHIVE/{YYYY-MM}/security/ snapshot + CALENDAR hatırlatması.",
            "nist_csf": ["Recover", "Govern"],
            "n80053": ["AU-7", "CP-2"],
            "iso": ["A.5.33"],
            "cis": ["CIS-8"],
            "owasp": [],
            "dogrulama": "archive-loop skill + /arsivle komutu.",
            "gerekce": "Trend ve gap geçmişini korur.",
        },
    ],
    "FIREWALLS": [
        {
            "id": "CTRL-FW-001",
            "ad": "Egress allowlist politikası (doküman)",
            "aciklama": "Harici API çağrıları için izinli domain listesi (docs düzeyinde ASSESS).",
            "nist_csf": ["Protect"],
            "n80053": ["SC-7"],
            "iso": ["A.8.20"],
            "cis": ["CIS-12"],
            "owasp": ["A05:2021"],
            "dogrulama": "SECURITY_CONTEXT/trust-boundaries.md egress bölümü.",
            "gerekce": "Beklenmeyen veri sızıntısı / C2 benzeri çıkışı engelleme niyeti (detection map).",
        },
        {
            "id": "CTRL-FW-002",
            "ad": "CI network izolasyon notu",
            "aciklama": "GitHub Actions job’larında gereksiz network yok; secrets yalnızca ${{ secrets.* }}.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-7", "AC-4"],
            "iso": ["A.8.21"],
            "cis": ["CIS-12"],
            "owasp": [],
            "dogrulama": ".github/workflows/*.yml gözden geçirme checklist.",
            "gerekce": "Runner üzerinden yan kanal riskini azaltır.",
        },
        {
            "id": "CTRL-FW-003",
            "ad": "MCP stub varsayılan OFF",
            "aciklama": "Güvenlik MCP’leri example stub; canlı Semgrep/Snyk iddiası yok.",
            "nist_csf": ["Protect", "Govern"],
            "n80053": ["CM-7"],
            "iso": ["A.8.9"],
            "cis": ["CIS-4"],
            "owasp": ["A05:2021"],
            "dogrulama": ".cursor/mcp.security.stubs.example.json varlığı.",
            "gerekce": "Yanlışlıkla açık tarayıcı/tool yüzeyi oluşturmaz.",
        },
        {
            "id": "CTRL-FW-004",
            "ad": "Webhook imza doğrulama standardı",
            "aciklama": "Gelecek webhook entegrasyonları için HMAC doğrulama şablonu (IMPLEMENT kapsamı ayrı).",
            "nist_csf": ["Protect"],
            "n80053": ["SC-8", "IA-9"],
            "iso": ["A.8.24"],
            "cis": ["CIS-13"],
            "owasp": ["A07:2021"],
            "dogrulama": "Şablon ASSESSMENTS/webhook-hmac.md (plan).",
            "gerekce": "Sahte olay enjeksiyonunu önler.",
        },
        {
            "id": "CTRL-FW-005",
            "ad": "DNS/trust: yalnızca bilinen registry",
            "aciklama": "Bağımlılık ve container registry allowlist dokümanı.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-7", "SA-12"],
            "iso": ["A.5.21"],
            "cis": ["CIS-16"],
            "owasp": ["A06:2021"],
            "dogrulama": "SECURITY_RESEARCH veya CONTEXT notu.",
            "gerekce": "Tedarik zinciri DNS hijack yüzeyini daraltır.",
        },
        {
            "id": "CTRL-FW-006",
            "ad": "SSH/port yönetim politikası",
            "aciklama": "Repo’da açılacak servis yok; port açma talepleri ASSESS kaydı.",
            "nist_csf": ["Protect"],
            "n80053": ["CM-7", "SC-7"],
            "iso": ["A.8.20"],
            "cis": ["CIS-4"],
            "owasp": [],
            "dogrulama": "AGENTS.md: no web server runtime.",
            "gerekce": "Saldırı yüzeyini sıfırda tutar (stdlib otomasyon).",
        },
        {
            "id": "CTRL-FW-007",
            "ad": "WAF/CDN kontrolü (uygulanabilirlik notu)",
            "aciklama": "Bu repo için N/A; holding web varlıkları için pointer.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-7"],
            "iso": ["A.8.20"],
            "cis": ["CIS-13"],
            "owasp": ["A05:2021"],
            "dogrulama": "Gap: N/A bu repo; MATRIX’te işaretle.",
            "gerekce": "Kapsam kaymasını önler; yanlış WAF iddiası yok.",
        },
        {
            "id": "CTRL-FW-008",
            "ad": "API rate-limit beklentisi",
            "aciklama": "Gemini/OpenRouter istemcilerinde geri çekilme; anahtar ${VAR}.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-5"],
            "iso": ["A.8.16"],
            "cis": ["CIS-13"],
            "owasp": ["A04:2021"],
            "dogrulama": "scripts/*_client.py rate/retry okuması.",
            "gerekce": "Anahtar yakma ve DoS benzeri kötüye kullanımı sınırlar.",
        },
        {
            "id": "CTRL-FW-009",
            "ad": "İç/dış trafik sınıflandırması",
            "aciklama": "GitHub API vs public web vs LLM provider ayrımı.",
            "nist_csf": ["Identify"],
            "n80053": ["CA-3"],
            "iso": ["A.5.14"],
            "cis": ["CIS-12"],
            "owasp": [],
            "dogrulama": "trust-boundaries.md tablosu.",
            "gerekce": "Firewall kurallarının semantik haritası.",
        },
        {
            "id": "CTRL-FW-010",
            "ad": "Host firewall baseline (ASSESS)",
            "aciklama": "Geliştirici host için varsayılan deny inbound checklist.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-7", "CM-6"],
            "iso": ["A.8.9"],
            "cis": ["CIS-4"],
            "owasp": [],
            "dogrulama": "ASSESSMENTS checklist satırı.",
            "gerekce": "Yanlışlıkla açık servis riskini düşürür.",
        },
        {
            "id": "CTRL-FW-011",
            "ad": "TLS zorunluluğu (harici)",
            "aciklama": "HTTPS-only harici çağrılar; cleartext yasak.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-8", "SC-13"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "Client kodunda http:// yok tarama (exclude katalog).",
            "gerekce": "Transit gizlilik ve bütünlük.",
        },
        {
            "id": "CTRL-FW-012",
            "ad": "Segregasyon: katalog vs runtime",
            "aciklama": "katalog/ CI/secret_scan skip; runtime scripts/ izole.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-2", "CM-7"],
            "iso": ["A.8.22"],
            "cis": ["CIS-12"],
            "owasp": [],
            "dogrulama": "secret_scan SKIP_DIRS.",
            "gerekce": "Vendored gürültü ve yanlış pozitifleri ayırır.",
        },
    ],
    "ENCRYPTION": [
        {
            "id": "CTRL-ENC-001",
            "ad": "Secret at-rest: repo’da plaintext yok",
            "aciklama": "Gerçek secret commit yasak; yalnızca ${VAR}|vault://|op://|<REDACTED>.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-28", "IA-5"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "python3 scripts/secret_scan.py.",
            "gerekce": "Sızıntı ve credential stuffing yüzeyini keser.",
        },
        {
            "id": "CTRL-ENC-002",
            "ad": "Transit TLS 1.2+",
            "aciklama": "Harici API’lerde TLS; zayıf cipher önerisi yok (ASSESS).",
            "nist_csf": ["Protect"],
            "n80053": ["SC-8", "SC-13"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "Client kütüphaneleri HTTPS kullanımı.",
            "gerekce": "Transit gizlilik.",
        },
        {
            "id": "CTRL-ENC-003",
            "ad": "Anahtar yaşam döngüsü (doküman)",
            "aciklama": "Rotasyon, sahiplik, iptal prosedürü — vault:// pointer.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-12", "SC-17"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": [],
            "dogrulama": "ENCRYPTION/key-lifecycle.md (bu kontrol + README pointer).",
            "gerekce": "Eski anahtarların sürünmesini engeller.",
        },
        {
            "id": "CTRL-ENC-004",
            "ad": "Kripto çeviklik — algoritma envanteri",
            "aciklama": "Kullanılan/planlanan algoritmalar listesi; zayıf alg. yasak listesi.",
            "nist_csf": ["Protect", "Identify"],
            "n80053": ["SC-13"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "crypto-agility skill references.",
            "gerekce": "Algoritma kırıldığında hızlı geçiş.",
        },
        {
            "id": "CTRL-ENC-005",
            "ad": "GitHub Actions secret şifreleme varsayımı",
            "aciklama": "Secrets GitHub encrypted secrets; log’a echo yasak.",
            "nist_csf": ["Protect"],
            "n80053": ["IA-5", "AU-9"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "Workflow’larda echo ${{ secrets.* }} yok.",
            "gerekce": "CI log sızıntısını önler.",
        },
        {
            "id": "CTRL-ENC-006",
            "ad": "Dosya şifreleme (hassas export)",
            "aciklama": "Confidential sınıfı export’lar için şifreli arşiv politikası.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-28", "MP-4"],
            "iso": ["A.8.10"],
            "cis": ["CIS-3"],
            "owasp": [],
            "dogrulama": "CANVA_OPS/exports politikası + data-classes.",
            "gerekce": "Dışa aktarımda veri koruması.",
        },
        {
            "id": "CTRL-ENC-007",
            "ad": "Hash bütünlük (SBOM/artifact)",
            "aciklama": "Yayınlanan artefaktlar için SHA-256 kaydı.",
            "nist_csf": ["Protect"],
            "n80053": ["SI-7"],
            "iso": ["A.8.25"],
            "cis": ["CIS-16"],
            "owasp": ["A08:2021"],
            "dogrulama": "validate integrity katmanı / holding stamp.",
            "gerekce": "Kurcalama tespitini sağlar.",
        },
        {
            "id": "CTRL-ENC-008",
            "ad": "Özel anahtar yok (repo)",
            "aciklama": "BEGIN PRIVATE KEY blokları yasak; scanner flag.",
            "nist_csf": ["Protect"],
            "n80053": ["IA-5", "SC-12"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "secret_scan private_key_block.",
            "gerekce": "Anahtar sızıntısı felaketini engeller.",
        },
        {
            "id": "CTRL-ENC-009",
            "ad": "JWT/Bearer log redaksiyonu",
            "aciklama": "Bearer token’lar log/raporda <REDACTED>.",
            "nist_csf": ["Protect"],
            "n80053": ["AU-9", "SI-12"],
            "iso": ["A.8.15"],
            "cis": ["CIS-8"],
            "owasp": ["A02:2021"],
            "dogrulama": "secret_scan bearer_jwt_like.",
            "gerekce": "Oturum token sızıntısını keser.",
        },
        {
            "id": "CTRL-ENC-010",
            "ad": "Disk şifreleme (host ASSESS)",
            "aciklama": "Geliştirici/CI disk FDE beklentisi (org politikası).",
            "nist_csf": ["Protect"],
            "n80053": ["SC-28"],
            "iso": ["A.8.1"],
            "cis": ["CIS-3"],
            "owasp": [],
            "dogrulama": "ORG politikası pointer.",
            "gerekce": "Cihaz kaybında veri koruması.",
        },
        {
            "id": "CTRL-ENC-011",
            "ad": "Şifre hash politikası (uygulama N/A)",
            "aciklama": "Bu repo auth DB yok; gelecek uygulamalar için Argon2/bcrypt standardı notu.",
            "nist_csf": ["Protect"],
            "n80053": ["IA-5"],
            "iso": ["A.8.5"],
            "cis": ["CIS-5"],
            "owasp": ["A02:2021"],
            "dogrulama": "Gap N/A + COMPLIANCE notu.",
            "gerekce": "Kapsam netliği; yanlış kontrol iddiası yok.",
        },
        {
            "id": "CTRL-ENC-012",
            "ad": "Kriptografik rastgelelik (token üretimi)",
            "aciklama": "Gerekirse secrets modülü; zayıf PRNG yasak listesi.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-12", "SC-13"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "Kod inceleme ASSESS checklist.",
            "gerekce": "Tahmin edilebilir token riskini azaltır.",
        },
    ],
    "CHANGE": [
        {
            "id": "CTRL-CH-001",
            "ad": "PR zorunlu inceleme (branch protection ASSESS)",
            "aciklama": "main’e doğrudan push yok; PR + review beklentisi.",
            "nist_csf": ["Protect", "Govern"],
            "n80053": ["CM-3", "CM-5"],
            "iso": ["A.8.32"],
            "cis": ["CIS-16"],
            "owasp": [],
            "dogrulama": "GitHub branch protection ASSESS notu ORG/.",
            "gerekce": "Kontrolsüz değişiklik riskini düşürür.",
        },
        {
            "id": "CTRL-CH-002",
            "ad": "CI validate gate",
            "aciklama": "validate.yml / validate-components.yml her PR’da.",
            "nist_csf": ["Protect", "Detect"],
            "n80053": ["SI-2", "CM-4"],
            "iso": ["A.8.25"],
            "cis": ["CIS-16"],
            "owasp": ["A08:2021"],
            "dogrulama": ".github/workflows/validate.yml.",
            "gerekce": "Bozuk yapılandırma main’e girmez.",
        },
        {
            "id": "CTRL-CH-003",
            "ad": "Secret scan gate",
            "aciklama": "secret_scan.py hook/CI; failClosed IDE, fail-open eksik script.",
            "nist_csf": ["Protect", "Detect"],
            "n80053": ["SI-4", "IA-5"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "scripts/secret_scan.py --self-test.",
            "gerekce": "Secret commit’i erken yakalar.",
        },
        {
            "id": "CTRL-CH-004",
            "ad": "Ethics check gate",
            "aciklama": "ethics_check.py offensive pattern taraması.",
            "nist_csf": ["Govern"],
            "n80053": ["PL-4"],
            "iso": ["A.5.1"],
            "cis": ["CIS-14"],
            "owasp": [],
            "dogrulama": "scripts/ethics_check.py --self-test.",
            "gerekce": "Dual-use içerik üretimini engeller.",
        },
        {
            "id": "CTRL-CH-005",
            "ad": "MODE=IMPLEMENT açık kapsam",
            "aciklama": "IMPLEMENT yalnız kullanıcı kapsamı + STATE güncellemesi.",
            "nist_csf": ["Govern"],
            "n80053": ["CM-3"],
            "iso": ["A.8.32"],
            "cis": ["CIS-16"],
            "owasp": [],
            "dogrulama": "SECURITY/STATE.md.",
            "gerekce": "Sessiz prod değişikliği yok.",
        },
        {
            "id": "CTRL-CH-006",
            "ad": "Changelog / AUDIT satırı (anlamlı tur)",
            "aciklama": "Anlamlı güvenlik turlarında AUDIT_LOG tek satır (spam yok).",
            "nist_csf": ["Govern", "Detect"],
            "n80053": ["AU-2"],
            "iso": ["A.8.15"],
            "cis": ["CIS-8"],
            "owasp": [],
            "dogrulama": "AUDIT_LOG.jsonl örnek satır.",
            "gerekce": "İzlenebilirlik vs gürültü dengesi.",
        },
        {
            "id": "CTRL-CH-007",
            "ad": "Dependabot/actions pin ASSESS",
            "aciklama": "GitHub Actions major pin; dependabot PR incelemesi.",
            "nist_csf": ["Protect"],
            "n80053": ["SA-12", "CM-2"],
            "iso": ["A.5.21"],
            "cis": ["CIS-16"],
            "owasp": ["A06:2021"],
            "dogrulama": "dependabot PR listesi + workflow uses: pin.",
            "gerekce": "Tedarik zinciri sürprizlerini azaltır.",
        },
        {
            "id": "CTRL-CH-008",
            "ad": "Geri alma prosedürü",
            "aciklama": "git revert / restore prosedürü; force-push yasak (agent kuralı).",
            "nist_csf": ["Recover"],
            "n80053": ["CM-3", "CP-10"],
            "iso": ["A.8.32"],
            "cis": ["CIS-16"],
            "owasp": [],
            "dogrulama": "CHANGE/rollback.md pointer.",
            "gerekce": "Hatalı değişiklikte hızlı toparlanma.",
        },
        {
            "id": "CTRL-CH-009",
            "ad": "Doküman vs kod ayrımı",
            "aciklama": "FAZ genişlemesi docs/controls; runtime scripts ayrı PR tercihi.",
            "nist_csf": ["Govern"],
            "n80053": ["CM-4"],
            "iso": ["A.5.8"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "PR kapsam notu.",
            "gerekce": "İnceleme yükünü yönetilebilir tutar.",
        },
        {
            "id": "CTRL-CH-010",
            "ad": "FEATURE branch adlandırma",
            "aciklama": "cursor/*-<id> şablonu; case collision yok.",
            "nist_csf": ["Govern"],
            "n80053": ["CM-2"],
            "iso": ["A.8.9"],
            "cis": ["CIS-16"],
            "owasp": [],
            "dogrulama": "Mevcut branch listesi.",
            "gerekce": "Çakışma ve kayıp iş riskini düşürür.",
        },
        {
            "id": "CTRL-CH-011",
            "ad": "Bot commit sınırları",
            "aciklama": "CI botları yalnız bilinen dosyaları (AUDIT/HOLDING) günceller.",
            "nist_csf": ["Protect"],
            "n80053": ["CM-5", "AC-6"],
            "iso": ["A.8.32"],
            "cis": ["CIS-5"],
            "owasp": [],
            "dogrulama": "Workflow commit path filter ASSESS.",
            "gerekce": "Beklenmeyen bot yazımı engellenir.",
        },
        {
            "id": "CTRL-CH-012",
            "ad": "Spec validate (creative+security)",
            "aciklama": "spec_validate.py self-test; yapısal bütünlük.",
            "nist_csf": ["Protect"],
            "n80053": ["CM-4", "SI-7"],
            "iso": ["A.8.25"],
            "cis": ["CIS-16"],
            "owasp": [],
            "dogrulama": "python3 scripts/spec_validate.py --self-test.",
            "gerekce": "Şablon sapmasını erken yakalar.",
        },
    ],
    "TRANSPARENT_CODE": [
        {
            "id": "CTRL-TC-001",
            "ad": "Kaynak görünürlüğü — stdlib only runtime",
            "aciklama": "Çalışan kod Python stdlib; gizli native blob yok.",
            "nist_csf": ["Identify", "Protect"],
            "n80053": ["SA-15", "CM-8"],
            "iso": ["A.8.25"],
            "cis": ["CIS-16"],
            "owasp": ["A08:2021"],
            "dogrulama": "AGENTS.md + scripts/ import tarama.",
            "gerekce": "Tedarik ve denetim şeffaflığı.",
        },
        {
            "id": "CTRL-TC-002",
            "ad": "Karar gerekçesi zorunlu alan",
            "aciklama": "Kontrol kartlarında savunma_gerekçesi boş olamaz.",
            "nist_csf": ["Govern"],
            "n80053": ["AU-3"],
            "iso": ["A.5.8"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "Seed script / QA checklist.",
            "gerekce": "Kara kutu güvenlik kararlarını önler.",
        },
        {
            "id": "CTRL-TC-003",
            "ad": "ATT&CK yalnız detection etiketi",
            "aciklama": "attack_detect alanı howto değil; D3FEND ile eşleşir.",
            "nist_csf": ["Detect"],
            "n80053": ["SI-4"],
            "iso": ["A.8.16"],
            "cis": ["CIS-8"],
            "owasp": [],
            "dogrulama": "ethics_check + peer review.",
            "gerekce": "Etik sınırın teknik ifadesi.",
        },
        {
            "id": "CTRL-TC-004",
            "ad": "Prompt/skill boyut sinyali",
            "aciklama": "≥900B tek pront RED; hybrid skill+refs.",
            "nist_csf": ["Govern"],
            "n80053": ["PL-2"],
            "iso": ["A.5.1"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "CILT14 + IS-LISTESI notu.",
            "gerekce": "Bakım ve güvenlik incelemesi ölçeklenebilir kalır.",
        },
        {
            "id": "CTRL-TC-005",
            "ad": "Lisans/provenance notu",
            "aciklama": "katalog/ MIT vendored; attribution korunur.",
            "nist_csf": ["Identify"],
            "n80053": ["SA-12"],
            "iso": ["A.5.20"],
            "cis": ["CIS-16"],
            "owasp": ["A06:2021"],
            "dogrulama": "katalog README / LICENSE.",
            "gerekce": "Yasal ve tedarik şeffaflığı.",
        },
        {
            "id": "CTRL-TC-006",
            "ad": "Hook davranış dokümantasyonu",
            "aciklama": "fail-open vs failClosed yazılı; sürpriz yok.",
            "nist_csf": ["Govern"],
            "n80053": ["CM-6"],
            "iso": ["A.8.9"],
            "cis": ["CIS-4"],
            "owasp": [],
            "dogrulama": ".cursor/hooks.json + scanner docstring.",
            "gerekce": "Operasyonel öngörülebilirlik.",
        },
        {
            "id": "CTRL-TC-007",
            "ad": "Raporlarda kanıt yolu",
            "aciklama": "Her gap satırı evidence path ister.",
            "nist_csf": ["Detect", "Govern"],
            "n80053": ["AU-6", "CA-7"],
            "iso": ["A.5.35"],
            "cis": ["CIS-8"],
            "owasp": ["A09:2021"],
            "dogrulama": "GAP-TEMPLATE.md.",
            "gerekce": "İddia ≠ kanıt ayrımı.",
        },
        {
            "id": "CTRL-TC-008",
            "ad": "Redaksiyon standardı",
            "aciklama": "Örneklerde sahte secret bile yasak; <REDACTED>.",
            "nist_csf": ["Protect"],
            "n80053": ["SI-12"],
            "iso": ["A.5.34"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "secret_scan patterns.",
            "gerekce": "Eğitim materyalinden sızıntı yok.",
        },
        {
            "id": "CTRL-TC-009",
            "ad": "Agent çıktı sözleşmesi",
            "aciklama": "Damga + denetim + öğrenim satırı (Holding).",
            "nist_csf": ["Govern"],
            "n80053": ["AU-3"],
            "iso": ["A.5.8"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "CLAUDE.md çıktı sözleşmesi.",
            "gerekce": "Zincirlenebilir öğrenme ve denetim.",
        },
        {
            "id": "CTRL-TC-010",
            "ad": "Kod yorumunda güvenlik iddiası yok",
            "aciklama": "“Bu güvenli” yorumu yerine kontrol ID referansı.",
            "nist_csf": ["Govern"],
            "n80053": ["SA-15"],
            "iso": ["A.8.25"],
            "cis": ["CIS-16"],
            "owasp": [],
            "dogrulama": "Code review checklist.",
            "gerekce": "Yeşil yıkama (security theater) önleme.",
        },
        {
            "id": "CTRL-TC-011",
            "ad": "Matris ↔ kontrol çift yönlü link",
            "aciklama": "matrix.md her kontrolü listeler; kontrol matrix’e pointer.",
            "nist_csf": ["Govern"],
            "n80053": ["CA-2"],
            "iso": ["A.5.35"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "SECURITY_MATRIX/matrix.md.",
            "gerekce": "Gap analizinde tek kaynak.",
        },
        {
            "id": "CTRL-TC-012",
            "ad": "Araştırma kaynak zorunluluğu",
            "aciklama": "SECURITY_RESEARCH notlarında URL/kaynak.",
            "nist_csf": ["Identify"],
            "n80053": ["PM-15"],
            "iso": ["A.5.7"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "SECURITY_RESEARCH/*.md frontmatter.",
            "gerekce": "Uydurma uzman/ranking yasaklanır.",
        },
    ],
    "CONDITIONAL": [
        {
            "id": "CTRL-CD-001",
            "ad": "Koşullu: CANVA:ON olmadan mutate yok",
            "aciklama": "Canva yazma yalnız flag + OAuth; aksi BRIEF-ONLY.",
            "nist_csf": ["Protect", "Govern"],
            "n80053": ["AC-3", "AC-24"],
            "iso": ["A.5.15"],
            "cis": ["CIS-6"],
            "owasp": ["A01:2021"],
            "dogrulama": "STATE.md flag + AGENTS.md.",
            "gerekce": "Yanlışlıkla tasarım mutasyonu engellenir.",
        },
        {
            "id": "CTRL-CD-002",
            "ad": "Koşullu: MODE=IMPLEMENT kapsamı",
            "aciklama": "IMPLEMENT yalnız listelenmiş kontrol ID’leri.",
            "nist_csf": ["Govern"],
            "n80053": ["CM-3", "AC-3"],
            "iso": ["A.8.32"],
            "cis": ["CIS-16"],
            "owasp": [],
            "dogrulama": "TASKS/ veya komut argümanı.",
            "gerekce": "Kapsam taşmasını önler.",
        },
        {
            "id": "CTRL-CD-003",
            "ad": "Koşullu: ANTHROPIC/GEMINI anahtarı yoksa dry-run",
            "aciklama": "API key yok → iskelet çıktı; üretilmiş secret yok.",
            "nist_csf": ["Protect"],
            "n80053": ["AC-3", "IA-5"],
            "iso": ["A.8.5"],
            "cis": ["CIS-5"],
            "owasp": [],
            "dogrulama": "daily_agency / llm clients dry-run.",
            "gerekce": "Ücretli/gizli çağrı sürprizi yok.",
        },
        {
            "id": "CTRL-CD-004",
            "ad": "Koşullu: GITHUB_TOKEN yoksa static holding",
            "aciklama": "holding_report static mode.",
            "nist_csf": ["Protect"],
            "n80053": ["AC-3"],
            "iso": ["A.5.15"],
            "cis": ["CIS-5"],
            "owasp": [],
            "dogrulama": "holding_report.py davranış notu.",
            "gerekce": "Yetkisiz API zenginleştirmesi yok.",
        },
        {
            "id": "CTRL-CD-005",
            "ad": "Koşullu: ethics KALDI → dur",
            "aciklama": "ethics_check KALDI ise üretim durur / reddeder.",
            "nist_csf": ["Govern", "Protect"],
            "n80053": ["SI-4", "IR-4"],
            "iso": ["A.5.1"],
            "cis": ["CIS-14"],
            "owasp": [],
            "dogrulama": "05-ethics-guardrail + /etik-denetim.",
            "gerekce": "Zararlı içeriğin yayılmasını keser.",
        },
        {
            "id": "CTRL-CD-006",
            "ad": "Koşullu: secret KALDI → commit engeli",
            "aciklama": "secret_scan bulgusu → düzeltmeden ilerleme yok.",
            "nist_csf": ["Protect"],
            "n80053": ["IA-5", "SI-4"],
            "iso": ["A.8.24"],
            "cis": ["CIS-3"],
            "owasp": ["A02:2021"],
            "dogrulama": "Hook + CLI exit 1.",
            "gerekce": "Credential sızıntısını durdurur.",
        },
        {
            "id": "CTRL-CD-007",
            "ad": "Koşullu: production deploy yok (bu repo)",
            "aciklama": "npx convex deploy vb. yok; sadece doküman/otomasyon.",
            "nist_csf": ["Protect"],
            "n80053": ["CM-7"],
            "iso": ["A.8.9"],
            "cis": ["CIS-4"],
            "owasp": [],
            "dogrulama": "AGENTS.md runtime tanımı.",
            "gerekce": "Yanlış prod etkisi sıfır.",
        },
        {
            "id": "CTRL-CD-008",
            "ad": "Koşullu: parallel agent izolasyonu",
            "aciklama": "Canva senaryoları SCENARIOS/{urun}/{n}/ altında.",
            "nist_csf": ["Protect"],
            "n80053": ["SC-2", "AC-4"],
            "iso": ["A.8.22"],
            "cis": ["CIS-12"],
            "owasp": [],
            "dogrulama": "SCENARIOS/ yapı.",
            "gerekce": "Çapraz kontaminasyon yok.",
        },
        {
            "id": "CTRL-CD-009",
            "ad": "Koşullu: IR severity ≥ yüksek → exec bilgilendirme",
            "aciklama": "Playbook’ta severity eşiği ve iletişim listesi.",
            "nist_csf": ["Respond"],
            "n80053": ["IR-4", "IR-6"],
            "iso": ["A.5.24"],
            "cis": ["CIS-17"],
            "owasp": [],
            "dogrulama": "incident-response playbook.",
            "gerekce": "Eskalasyon gecikmesini azaltır.",
        },
        {
            "id": "CTRL-CD-010",
            "ad": "Koşullu: compliance paket yalnız map",
            "aciklama": "ASSESS-ONLY’de compliance = eşleme; sertifika iddiası yok.",
            "nist_csf": ["Govern"],
            "n80053": ["CA-2"],
            "iso": ["A.5.35"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "/compliance-paket komutu.",
            "gerekce": "Sahte sertifikasyon iddiasını önler.",
        },
        {
            "id": "CTRL-CD-011",
            "ad": "Koşullu: research kaynaksız yayın yok",
            "aciklama": "EXPERTS/SECURITY_RESEARCH kaynaksız satır eklenmez.",
            "nist_csf": ["Govern"],
            "n80053": ["PM-15"],
            "iso": ["A.5.7"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "EXPERTS/_SEED.md sources sütunu.",
            "gerekce": "Uydurma otorite riskini keser.",
        },
        {
            "id": "CTRL-CD-012",
            "ad": "Koşullu: arşiv ay sonu",
            "aciklama": "/arsivle yalnızca aylık veya açık talep.",
            "nist_csf": ["Recover", "Govern"],
            "n80053": ["AU-7"],
            "iso": ["A.5.33"],
            "cis": ["CIS-8"],
            "owasp": [],
            "dogrulama": "CALENDAR/ + ARCHIVE/.",
            "gerekce": "Arşiv şişkinliğini önler.",
        },
        {
            "id": "CTRL-CD-013",
            "ad": "Koşullu: MCP enable kullanıcı onayı",
            "aciklama": "Güvenlik MCP canlıya alınmadan önce kullanıcı enable.",
            "nist_csf": ["Protect", "Govern"],
            "n80053": ["AC-3", "CM-7"],
            "iso": ["A.8.9"],
            "cis": ["CIS-4"],
            "owasp": ["A05:2021"],
            "dogrulama": "mcp stubs example only.",
            "gerekce": "Yetkisiz tool yüzeyi açılmaz.",
        },
        {
            "id": "CTRL-CD-014",
            "ad": "Koşullu: gap owner boşsa escalate",
            "aciklama": "Gap satırında Owner boş → Security Architect kuyruğu.",
            "nist_csf": ["Govern"],
            "n80053": ["CA-7", "PM-9"],
            "iso": ["A.5.2"],
            "cis": ["CIS-1"],
            "owasp": [],
            "dogrulama": "GAP-TEMPLATE + ORG/ROLES.",
            "gerekce": "Sahipsiz risk birikmez.",
        },
        {
            "id": "CTRL-CD-015",
            "ad": "Koşullu: dual-OS çakışma önceliği",
            "aciklama": "Security ethics vs Canva üretimi çakışırsa ethics kazanır.",
            "nist_csf": ["Govern"],
            "n80053": ["PL-4"],
            "iso": ["A.5.1"],
            "cis": ["CIS-14"],
            "owasp": [],
            "dogrulama": "AGENTS.md dual sections + ethics rule.",
            "gerekce": "İş hızı etik sınırın üstüne çıkamaz.",
        },
    ],
}


def render_control(c: dict) -> str:
    y = [
        f"id: {c['id']}",
        f"ad: {c['ad']}",
        f"açıklama: {c['aciklama']}",
        f"NIST_CSF: {c['nist_csf']}",
        f"800-53: {c['n80053']}",
        f"ISO27001: {c['iso']}",
        f"CIS: {c['cis']}",
        f"OWASP: {c['owasp']}",
        "status: assess",
        "mode: ASSESS-ONLY",
        f"doğrulama_yöntemi: {c['dogrulama']}",
        f"savunma_gerekçesi: {c['gerekce']}",
    ]
    body = "\n".join(
        [
            f"# {c['id']} — {c['ad']}",
            "",
            "```yaml",
            *y,
            "```",
            "",
            "## Açıklama",
            c["aciklama"],
            "",
            "## Doğrulama (ASSESS-ONLY)",
            f"- {c['dogrulama']}",
            "",
            "## Savunma gerekçesi",
            c["gerekce"],
            "",
            GUARD,
            "",
        ]
    )
    return body


def write_catalogs() -> list[tuple[str, str]]:
    written: list[tuple[str, str]] = []
    for folder, controls in CATALOGS.items():
        d = ROOT / folder
        d.mkdir(parents=True, exist_ok=True)
        for c in controls:
            path = d / f"{c['id']}.md"
            path.write_text(render_control(c), encoding="utf-8")
            written.append((folder, c["id"]))
        # update README index
        lines = [
            f"# {folder}",
            "",
            "Starter control catalog (FAZ 3 expansion). MODE=`ASSESS-ONLY`.",
            "",
            "| ID | Ad | NIST CSF |",
            "|----|----|----------|",
        ]
        for c in controls:
            csf = ", ".join(c["nist_csf"])
            lines.append(f"| [{c['id']}]({c['id']}.md) | {c['ad']} | {csf} |")
        if folder == "LAYERS":
            lines.append(
                "| [CTRL-SAMPLE-ACCESS](CTRL-SAMPLE-ACCESS.md) | Least privilege (sample) | Protect |"
            )
        lines.extend(["", GUARD, ""])
        (d / "README.md").write_text("\n".join(lines), encoding="utf-8")
    return written


def write_matrix(written: list[tuple[str, str]]) -> None:
    mx = ROOT / "SECURITY_MATRIX"
    mx.mkdir(parents=True, exist_ok=True)
    rows = [
        "# SECURITY_MATRIX — matrix.md",
        "",
        "Kontrol kataloğu indeksi (FAZ 5). Gap analizi için `GAP-TEMPLATE.md`.",
        "",
        "| Katalog | Kontrol | Dosya |",
        "|---------|---------|-------|",
    ]
    for folder, cid in written:
        rows.append(f"| {folder} | {cid} | `../{folder}/{cid}.md` |")
    rows.append(
        "| LAYERS | CTRL-SAMPLE-ACCESS | `../LAYERS/CTRL-SAMPLE-ACCESS.md` |"
    )
    rows.extend(
        [
            "",
            "## Kullanım",
            "1. `/gap-analizi` → bu matris + CONTEXT",
            "2. `/kontrol-uret` → yeni CTRL-* kartı (alan sözleşmesi: compliance-mapper)",
            "3. status: planned|assess|implement|verify",
            "",
            GUARD,
            "",
        ]
    )
    (mx / "matrix.md").write_text("\n".join(rows), encoding="utf-8")
    (mx / "README.md").write_text(
        "\n".join(
            [
                "# SECURITY_MATRIX",
                "",
                "- `matrix.md` — kontrol indeksi",
                "- `GAP-TEMPLATE.md` — gap şablonu",
                "",
                "MODE=`ASSESS-ONLY` default.",
                "",
                GUARD,
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> int:
    written = write_catalogs()
    write_matrix(written)
    print(f"OK controls={len(written)} catalogs={len(CATALOGS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
